site_name: Mucosal Immunology Bioinformatics Hub
repo_url: https://mucosal-immunology-lab.github.io/bioinformatics-hub/
repo_name: Mucosal-Immunology-Lab/bioinformatic-hub

nav:
  - Home: index.md
  - Bulk Transcriptomics: RNAseq/rnaseq-nfcore.md
  - Microbiome:
    - 16S rRNA amplicon:
      - DADA2 pipeline: Microbiome/dada2_pipeline.md
  - LCMS Analysis:
    - Overview: LCMS/lcms-analysis.md
    - 1. Raw Data Processing with MS-DIAL: LCMS/msdial-processing.md
    - 2. Peak Matrix Processing: LCMS/pmp-quality-control.md
    - 3. Secondary Feature Annotation: LCMS/secondary-feature-annotation.md
    - 4. Manual Peak Curation: LCMS/manual-peak-curation.md
  - Nextflow Pipelines:
    - Single-cell RNAseq: NextFlow/scRNAseq.md
    - DADA2 16S rRNA: NextFlow/dada2_16S.md
  - Utilities:
    - Handling sequencing data:
      - Data best practices: Utilities/data-best-practices.md
      - Converting NovaSeq outputs: Utilities/convert-raw-novaseq-outputs.md
      - SRA sequencing data submission: Utilities/sra-data-submission.md
    - Monash data storage:
      - Market storage: Utilities/market-storage.md
      - Vault storage: Utilities/vault-storage.md
  - Public Datasets: PublicDatasets/public-datasets.md

theme:
  name: material
  logo: assets/mil_logo.png
  features:
    - content.code.copy

extra_css:
  - stylesheet/extra.css

markdown_extensions: 
  - pymdownx.emoji
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.tables
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  
extra:
  analytics:
    provider: google
    property: G-7HN0DB92MT

# Analytics:
# https://analytics.google.com/analytics/web/provision/#/p469513623/reports/intelligenthome 