site_name: Mucosal Immunology Bioinformatics Hub
repo_url: https://mucosal-immunology-lab.github.io/bioinformatics-hub/
repo_name: Mucosal-Immunology-Lab/bioinformatic-hub

nav:
  - Home: index.md
  - Bulk Transcriptomics: RNAseq/rnaseq-nfcore.md
  - Nextflow Pipelines: 
    - nf-mucimmuno: NextFlow/nf-mucimmuno.md
    - Single-cell RNAseq: NextFlow/scRNAseq.md
  - Public Datasets: PublicDatasets/public-datasets.md

theme:
  name: material
  logo: assets/mil_logo.png
  features:
    - content.code.copy

extra_css:
  - stylesheet/extra.css

markdown_extensions: 
  - pymdownx.emoji
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.tables
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji
  
extra:
  analytics:
    provider: google
    property: G-7HN0DB92MT

# Analytics:
# https://analytics.google.com/analytics/web/provision/#/p469513623/reports/intelligenthome 